version: '3.7'

services:
    mysql:
        container_name: mysql
        image: mysql:latest
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: polizario
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
        